ms:
  gateway:
    kafka:
      consumer:
        bootstrapServer: ${KAFKA_BOOTSTRAP_SERVER:0.0.0.0:9092}
        groupId: kafka-gateway
        topic: request-gateway-topic
      producer:
        bootstrapServer: ${KAFKA_BOOTSTRAP_SERVER:0.0.0.0:9092}
        resultTopic: result-gateway-topic
        errorTopic: error-gateway-topic

spring:
  h2:
    console:
      enabled: true